CREATE TABLE "user" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "login" varchar UNIQUE NOT NULL,
  "password_hash" varchar NOT NULL,
  "role" varchar NOT NULL
);

CREATE TABLE "car" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "model" varchar NOT NULL,
  "type" varchar NOT NULL,
  "condition" boolean DEFAULT true,
  "fuel_level" integer
);

CREATE TABLE "passenger_car" (
  "car_id" integer PRIMARY KEY,
  "seats" integer NOT NULL
);

CREATE TABLE "cargo_car" (
  "car_id" integer PRIMARY KEY,
  "load_capacity" float NOT NULL
);

CREATE TABLE "driver" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "passport" varchar NOT NULL,
  "car_id" integer UNIQUE NOT NULL,
  "user_id" integer NOT NULL
);

CREATE TABLE "request" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "required_type" varchar NOT NULL,
  "required_value" float NOT NULL,
  "destination" varchar NOT NULL,
  "status" varchar DEFAULT 'new',
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "trip" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "request_id" integer NOT NULL,
  "driver_id" integer NOT NULL,
  "is_completed" boolean DEFAULT false,
  "started_at" timestamp DEFAULT (now()),
  "finished_at" timestamp,
  "end_condition" boolean
);

ALTER TABLE "passenger_car" ADD FOREIGN KEY ("car_id") REFERENCES "car" ("id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "cargo_car" ADD FOREIGN KEY ("car_id") REFERENCES "car" ("id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "driver" ADD FOREIGN KEY ("car_id") REFERENCES "car" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "driver" ADD FOREIGN KEY ("user_id") REFERENCES "user" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "trip" ADD FOREIGN KEY ("request_id") REFERENCES "request" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "trip" ADD FOREIGN KEY ("driver_id") REFERENCES "driver" ("id") DEFERRABLE INITIALLY IMMEDIATE;
