services:
  app:
    build: .
    container_name: APP
    ports:
      - "$APP_PORT:7200"
    depends_on:
      - DB

  DB:
    container_name: DB
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: midnight
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: test_app
    ports:
      - "5432:5432"
    volumes:
      - ./car_base.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data: